package com.commerce.visualizer.utils;

public class Constants {

    public static final String[] ACTIVITY_TYPES = {
            "Activitats emmagatzematge",
            "Ensenyament",
            "Serveis a les empreses i oficines",
            "Arts gràfiques",
            "Activitats de la construcció",
            "Reparacions (Electrodomèstics i automòbils)",
            "Sanitat i assistència",
            "Maquinària",
            "Associacions",
            "Locals buits en venda i lloguer – reanalisi",
            "Vehicles",
            "Vestir",
            "Restaurants",
            "Pàrquings i garatges",
            "Locutoris",
            "Autoservei / Supermercat",
            "Altres",
            "Activitats industrials",
            "Locals buits en venda",
            "Bars / CIBERCAFÈ",
            "Farmàcies PARAFARMÀCIA",
            "Arranjaments",
            "Equipaments culturals i recreatius",
            "Centres d'estètica",
            "Serveis Socials",
            "Fruites i verdures",
            "Joieria, rellotgeria i bijuteria",
            "Perruqueries",
            "Drogueria i perfumeria",
            "Material equipament llar",
            "Basars",
            "Pa, pastisseria i làctics",
            "Activitats de transport",
            "Mobles i articles fusta i metall",
            "Serveis de telecomunicacions",
            "Plats preparats (no degustació)",
            "Bars especials amb actuació / Bars musicals / Discoteques / PUB",
            "Parament ferreteria",
            "Serveis de menjar take away MENJAR RÀPID",
            "Locals buits en lloguer",
            "Tintoreries",
            "Serveis d'allotjament",
            "Altres equipaments esportius",
            "Carn i Porc",
            "Begudes",
            "Herbolaris, dietètica i NUTRICIÓ",
            "Informàtica",
            "Aparells domèstics",
            "Veterinaris / Mascotes",
            "Música",
            "Finances i assegurances",
            "Activitats immobiliàries",
            "Equipaments religiosos",
            "Joguines i esports",
            "Manteniment, neteja i similars",
            "Administració",
            "Fotografia",
            "Gimnàs / fitnes",
            "Locals buits en venda i lloguer",
            "Combustibles i carburants",
            "Fabricació tèxtil",
            "Tabac i articles fumadors",
            "Merceria",
            "Floristeries",
            "Llibres, diaris i revistes",
            "Òptiques",
            "Ous i aus",
            "Agències de viatge",
            "Souvenirs",
            "Calçat i pell",
            "Xocolateries / Geladeries / Degustació",
            "Segells, monedes i antiguitats",
            "Peix i marisc",
            "Serveis de menjar i begudes",
            "Altres (per exemple VENDING)",
            "Altres",
            "Resta alimentació",
            "Souvenirs i basars",
            "Grans magatzems i hipermercats"
    };
}
